# Generated by Django 4.1.2 on 2022-11-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_korzina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('tovarnomi', models.CharField(max_length=100)),
                ('tovarnarxi', models.CharField(max_length=100)),
                ('tovarsoni', models.IntegerField()),
                ('tovarumumiynarx', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='korzina',
            name='tovarumumiynarx',
            field=models.CharField(default='', max_length=100),
        ),
    ]
