# Generated by Django 4.0.1 on 2022-12-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='data',
            field=models.BinaryField(),
        ),
    ]
