# Generated by Django 4.0.1 on 2022-12-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_video_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='data',
            field=models.CharField(max_length=99999999),
        ),
    ]
