# Generated by Django 4.0.1 on 2022-12-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_video_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='data',
            field=models.BinaryField(),
        ),
    ]
