# Generated by Django 3.1.7 on 2021-07-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.TextField()),
                ('meeting_title', models.TextField()),
                ('meeting_subject', models.TextField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
