# Generated by Django 3.1.7 on 2021-07-23 01:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 23, 1, 46, 24, 355023, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 23, 1, 46, 32, 805257, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
